name: Run Bruno Tests

on:
  workflow_dispatch:

jobs:
  bruno-test:
    name: Run Bruno CLI Tests
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Adjust Node version as needed

      # Install Bruno CLI dependencies
      - name: Install Dependencies
        run: |
          npm install
          
      - name: Run Bruno Tests
        env:
          REQ_URL_HTTPBIN: ${{ secrets.REQ_URL_HTTPBIN }}
          REQ_URL_FAKE: ${{ secrets.REQ_URL_FAKE }}
        run: |
          cd collection
          mkdir -p ./reports
          npx @usebruno/cli run ./ \
          --env-var "REQ_URL_FAKE=${REQ_URL_FAKE}" \
          --reporter-json reports/results.json \
          --reporter-html reports/Results.html

      # Upload the test report as an artifact
      - name: Upload Test Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Bruno Test Results
          path: reports/Results.html

      # (Optional) Post-run: Summary output
      - name: Display Test Run Summary
        if: always()
        run: echo "Bruno tests completed. HTML report is generated and uploaded as an artifact."